#create user from here https://demoqa.com/swagger/#/Account/AccountV1UserPost and not down userId from response
qa.user={userName for demoqa.com}
qa.password={Password for demoqa.com}
qa.userId={userId}

qa.baseUrl=https://demo.qa.com

# Full MS authorize URL ? paste exactly as given by your dev team
qa.auth.msAuthUrl=https://login.microsoftonline.com/xxxx/oauth2/v2.0/authorize?client_id=xxxx&scope=api://b0758764-cce0-4fdf-85ff-7bce46936815/User.Read&redirect_uri=http://localhost:3000/sso&response_mode=fragment&response_type=token&sso_reload=true

# Internal SSO base URL (path /authorize is appended by SsoTokenExchanger)
qa.auth.ssoUrl=https://demo.qa.com
